"""the question store's three tables

The first revision, and the whole of the schema § *The question store* draws. Autogenerated from
`edge/store/models.py` and read before it was committed: what it wrote is the three tables, two
indexes on the columns answers are read back by, the composite key that makes a push idempotent per
system, and the unique `external_annotation_id` that makes a pull idempotent. Nothing was adjusted.

Revision ID: 21068fe57bd9
Revises:
Create Date: 2026-08-25

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "21068fe57bd9"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "question",
        sa.Column(
            "question_id",
            sa.String(length=64),
            nullable=False,
            comment="Minted by `question_generate` over the question itself; everything joins on it.",
        ),
        sa.Column(
            "record_id",
            sa.String(length=64),
            nullable=False,
            comment="Which record it asks about. Indexed: answers are read back per record.",
        ),
        sa.Column(
            "run_id",
            sa.String(length=64),
            nullable=False,
            comment="Which pipeline run published it. A store outlives any one run.",
        ),
        sa.Column(
            "modality",
            sa.String(length=64),
            nullable=False,
            comment="The pair it was composed under, `name@version`; a question read under another is not the same question.",
        ),
        sa.Column(
            "profile",
            sa.String(length=64),
            nullable=False,
            comment="The other half of that pair, stamped the same way.",
        ),
        sa.Column(
            "payload",
            sa.JSON(),
            nullable=False,
            comment="The task payload as the annotation tool takes it: `data` and nothing else.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="When the store first held it. A re-publish does not move it.",
        ),
        sa.PrimaryKeyConstraint("question_id"),
    )
    op.create_index(
        op.f("ix_question_record_id"), "question", ["record_id"], unique=False
    )
    op.create_index(op.f("ix_question_run_id"), "question", ["run_id"], unique=False)
    op.create_table(
        "annotator_answer",
        sa.Column(
            "answer_id",
            sa.String(length=64),
            nullable=False,
            comment="The store's own id for this answer.",
        ),
        sa.Column(
            "question_id",
            sa.String(length=64),
            nullable=False,
            comment="Which question it answers. Indexed: answers are read back by question.",
        ),
        sa.Column(
            "annotator_id",
            sa.String(length=64),
            nullable=False,
            comment="Who answered. The overlap `aggregate` folds is a count of distinct values here.",
        ),
        sa.Column(
            "result",
            sa.JSON(),
            nullable=False,
            comment="The annotation's control values, verbatim. Only `answer_from_response` reads this shape.",
        ),
        sa.Column(
            "was_skipped",
            sa.Boolean(),
            nullable=False,
            comment="The annotator saw the question and declined it. Not a verdict, and not a missing row.",
        ),
        sa.Column(
            "lead_time_seconds",
            sa.Float(),
            nullable=True,
            comment="How long they took, where the tool reported it. An instrument the pilot reads.",
        ),
        sa.Column(
            "submitted_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="When they submitted it, by the annotation tool's clock.",
        ),
        sa.Column(
            "external_annotation_id",
            sa.String(length=64),
            nullable=True,
            comment="That tool's id for the annotation. Unique, which is what makes pulling twice a no-op.",
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["question.question_id"],
        ),
        sa.PrimaryKeyConstraint("answer_id"),
        sa.UniqueConstraint("external_annotation_id"),
    )
    op.create_index(
        op.f("ix_annotator_answer_question_id"),
        "annotator_answer",
        ["question_id"],
        unique=False,
    )
    op.create_table(
        "publication",
        sa.Column(
            "question_id",
            sa.String(length=64),
            nullable=False,
            comment="Which question was pushed. Half of the pair that makes the sync idempotent.",
        ),
        sa.Column(
            "external_system",
            sa.String(length=64),
            nullable=False,
            comment="Which annotation tool it went to; the other half of that pair.",
        ),
        sa.Column(
            "external_project_id",
            sa.String(length=64),
            nullable=True,
            comment="The project it landed in over there, where that system has projects.",
        ),
        sa.Column(
            "external_task_id",
            sa.String(length=64),
            nullable=True,
            comment="The id that system gave the task, which is why `question_id` also rides in `data`.",
        ),
        sa.Column(
            "status",
            sa.String(length=64),
            nullable=False,
            comment="What the push did, in the sync's own words.",
        ),
        sa.Column(
            "pushed_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="When it was pushed, by the syncing process's clock.",
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["question.question_id"],
        ),
        sa.PrimaryKeyConstraint("question_id", "external_system"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("publication")
    op.drop_index(
        op.f("ix_annotator_answer_question_id"), table_name="annotator_answer"
    )
    op.drop_table("annotator_answer")
    op.drop_index(op.f("ix_question_run_id"), table_name="question")
    op.drop_index(op.f("ix_question_record_id"), table_name="question")
    op.drop_table("question")
    # ### end Alembic commands ###
